version: '3.8'

services:

  database:
    container_name: database
    ports:
      - '5432:5432'
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      app_network:

  backend:
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - database
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
    container_name: frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - app_network

networks:
  app_network:
    name: app_network
